export enum PullTransactionType {
  BUSINESS = 'BUSINESS',
  CASH_BOX = 'CASH_BOX',
  CASH_BOX_TOPUP = 'CASH_BOX_TOPUP',
  CASH_BOX_TOPUP_TECH_ACC = 'CASH_BOX_TOPUP_TECH_ACC',
  REFERRAL = 'REFERRAL',
}
