export enum TransactionType {
  REINVEST = 'REINVEST',
  INVEST = 'INVEST',
  TOPUP = 'TOPUP',
  DEPOSIT = 'DEPOSIT',
  MANUAL_WITHDRAW = 'MANUAL_WITHDRAW',
  AUTO_WITHDRAW = 'AUTO_WITHDRAW',
  TRANSFER = 'TRANSFER',
  SWAP = 'SWAP',
}
